import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shoutout/shoutout.dart';

/// Example demonstrating offline-first capabilities
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive for offline queue and cache
  await Hive.initFlutter();

  // Register Hive adapters (generated by build_runner)
  // Hive.registerAdapter(QueuedRequestAdapter());

  runApp(const OfflineExampleApp());
}

class OfflineExampleApp extends StatelessWidget {
  const OfflineExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Shoutout Offline Example',
      home: const OfflineExample(),
    );
  }
}

class OfflineExample extends StatefulWidget {
  const OfflineExample({super.key});

  @override
  State<OfflineExample> createState() => _OfflineExampleState();
}

class _OfflineExampleState extends State<OfflineExample> {
  late ShoutoutClient client;
  late NetworkMonitor networkMonitor;
  late OfflineQueueManager queueManager;
  late CacheManager cacheManager;

  NetworkStatus? networkStatus;
  List<QueuedRequest> queuedRequests = [];
  Map<String, dynamic>? cacheStats;

  @override
  void initState() {
    super.initState();
    _initializeServices();
  }

  Future<void> _initializeServices() async {
    // 1. Configure Shoutout client
    final config = ShoutoutConfig(
      baseUrl: 'https://yoursite.frappe.cloud',
      enableLogging: true,
    );
    client = ShoutoutClient(config: config);

    // 2. Initialize Network Monitor
    networkMonitor = NetworkMonitor();
    networkMonitor.statusStream.listen((status) {
      setState(() {
        networkStatus = status;
      });
    });

    // 3. Initialize Cache Manager
    cacheManager = CacheManager();
    await cacheManager.initialize();

    // 4. Initialize Offline Queue Manager
    queueManager = OfflineQueueManager(
      dio: client.dio,
      networkMonitor: networkMonitor,
    );
    await queueManager.initialize();

    // Listen to queue results
    queueManager.resultsStream.listen((result) {
      print('Queue result: ${result.success ? "Success" : "Failed"}');
      _updateQueueDisplay();
    });

    _updateQueueDisplay();
    _updateCacheStats();
  }

  void _updateQueueDisplay() {
    setState(() {
      queuedRequests = queueManager.getAllRequests();
    });
  }

  Future<void> _updateCacheStats() async {
    final stats = await cacheManager.getStats();
    setState(() {
      cacheStats = stats;
    });
  }

  // Example 1: Fetch with cache
  Future<void> _fetchWithCache() async {
    try {
      final users = await cacheManager.getOrFetch(
        'users_list',
        () async {
          return await client.getList(
            'User',
            fields: ['name', 'email', 'full_name'],
            limitPageLength: 10,
          );
        },
        expiresIn: const Duration(minutes: 5),
      );

      print('Fetched ${users.length} users (from cache or network)');
      await _updateCacheStats();
    } catch (e) {
      print('Error fetching users: $e');
    }
  }

  // Example 2: Queue request for offline
  Future<void> _queueOfflineRequest() async {
    try {
      await queueManager.enqueueFromOptions(
        client.dio.options.compose(
          client.dio.options,
          '/api/method/frappe.desk.form.save.savedocs',
          data: {
            'doc': {
              'doctype': 'ToDo',
              'description': 'Test todo created offline',
              'status': 'Open',
            },
          },
        ).toOptions(),
        tag: 'create_todo',
        priority: 10,
      );

      print('Request queued for when connection is restored');
      _updateQueueDisplay();
    } catch (e) {
      print('Error queuing request: $e');
    }
  }

  // Example 3: Using Either pattern with failures
  Future<Either<Failure, List<dynamic>>> _fetchUsersWithEither() async {
    try {
      final users = await client.getList(
        'User',
        fields: ['name', 'email'],
        limitPageLength: 10,
      );
      return Right(users);
    } on ShoutoutException catch (e) {
      return Left(e.toFailure());
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Offline-First Example'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Network Status
            Card(
              child: ListTile(
                leading: Icon(
                  networkStatus?.isConnected ?? false
                      ? Icons.wifi
                      : Icons.wifi_off,
                  color: networkStatus?.isConnected ?? false
                      ? Colors.green
                      : Colors.red,
                ),
                title: Text(
                  networkStatus?.isConnected ?? false
                      ? 'Online'
                      : 'Offline',
                ),
                subtitle: Text(
                  'Type: ${networkStatus?.connectionType ?? "unknown"}\n'
                  'Quality: ${networkStatus?.quality ?? "unknown"}',
                ),
              ),
            ),

            const SizedBox(height: 16),

            // Cache Stats
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Cache Statistics',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text('Total: ${cacheStats?['total'] ?? 0}'),
                    Text('Valid: ${cacheStats?['valid'] ?? 0}'),
                    Text('Expired: ${cacheStats?['expired'] ?? 0}'),
                    const SizedBox(height: 8),
                    ElevatedButton(
                      onPressed: () async {
                        await cacheManager.cleanup();
                        await _updateCacheStats();
                      },
                      child: const Text('Cleanup Cache'),
                    ),
                  ],
                ),
              ),
            ),

            const SizedBox(height: 16),

            // Offline Queue
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Offline Queue (${queuedRequests.length})',
                      style: const TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),
                    ...queuedRequests.map((request) => ListTile(
                          title: Text('${request.method} ${request.url}'),
                          subtitle: Text(
                            'Retries: ${request.retryCount}/${request.maxRetries}',
                          ),
                          trailing: IconButton(
                            icon: const Icon(Icons.delete),
                            onPressed: () async {
                              await queueManager.removeRequest(request.id);
                              _updateQueueDisplay();
                            },
                          ),
                        )),
                  ],
                ),
              ),
            ),

            const SizedBox(height: 16),

            // Actions
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                ElevatedButton(
                  onPressed: _fetchWithCache,
                  child: const Text('Fetch with Cache'),
                ),
                ElevatedButton(
                  onPressed: _queueOfflineRequest,
                  child: const Text('Queue Offline Request'),
                ),
                ElevatedButton(
                  onPressed: () async {
                    await queueManager.processQueue();
                    _updateQueueDisplay();
                  },
                  child: const Text('Process Queue'),
                ),
                ElevatedButton(
                  onPressed: () async {
                    final result = await _fetchUsersWithEither();
                    result.fold(
                      (failure) =>
                          print('Failed with: ${failure.message}'),
                      (users) =>
                          print('Success: ${users.length} users'),
                    );
                  },
                  child: const Text('Fetch with Either'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    networkMonitor.dispose();
    queueManager.dispose();
    cacheManager.dispose();
    super.dispose();
  }
}
